# Generated by Django 5.2.7 on 2025-11-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=255, verbose_name="Ключ от календаря"),
                ),
            ],
            options={
                "verbose_name": "Календарь",
                "verbose_name_plural": "Календари",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время обновления"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активность"),
                ),
                (
                    "uid",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="UID мероприятия"
                    ),
                ),
                (
                    "date_from",
                    models.DateTimeField(
                        verbose_name="Дата и время начала мероприятия"
                    ),
                ),
                (
                    "date_till",
                    models.DateTimeField(
                        verbose_name="Дата и время завершения мероприятия"
                    ),
                ),
                ("title", models.TextField(verbose_name="Наименование мероприятия")),
                ("description", models.TextField(verbose_name="Описание мероприятия")),
                (
                    "url_calendar",
                    models.CharField(
                        max_length=255, verbose_name="Ссылка на мероприятие"
                    ),
                ),
                (
                    "star",
                    models.BooleanField(default=False, verbose_name="Со звездочкой"),
                ),
                ("slash", models.BooleanField(default=False, verbose_name="Со слэшем")),
                (
                    "all_event",
                    models.BooleanField(
                        default=False, verbose_name="Общее мероприятие"
                    ),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
            },
        ),
    ]
