# Generated by Django 5.2.7 on 2025-11-05 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активность"),
                ),
                (
                    "uid",
                    models.IntegerField(unique=True, verbose_name="ID мероприятия"),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, verbose_name="Наименование мероприятия"
                    ),
                ),
                (
                    "date_start",
                    models.DateTimeField(
                        verbose_name="Дата и время начала мероприятия"
                    ),
                ),
                (
                    "date_end",
                    models.DateTimeField(
                        verbose_name="Дата и время завершения мероприятия"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Описание мероприятия",
                    ),
                ),
                (
                    "url",
                    models.CharField(max_length=255, verbose_name="Ссылка на встречу"),
                ),
                (
                    "with_star",
                    models.BooleanField(default=False, verbose_name="Со звездочкой"),
                ),
                (
                    "with_stick",
                    models.BooleanField(default=False, verbose_name="С палочкой"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие",
                "verbose_name_plural": "События",
            },
        ),
    ]
