# Generated by Django 5.2.7 on 2025-12-01 07:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0003_event_users"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="users",
        ),
        migrations.AddField(
            model_name="event",
            name="users",
            field=models.ManyToManyField(
                blank=True, default=None, null=True, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
