# Generated by Django 5.2.7 on 2025-12-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0004_remove_event_users_event_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date_from",
            field=models.DateTimeField(
                blank=True, verbose_name="Дата и время начала мероприятия"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="date_till",
            field=models.DateTimeField(
                blank=True, verbose_name="Дата и время завершения мероприятия"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание мероприятия"),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.TextField(blank=True, verbose_name="Наименование мероприятия"),
        ),
        migrations.AlterField(
            model_name="event",
            name="url_calendar",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Ссылка на мероприятие"
            ),
        ),
    ]
