# Generated by Django 5.2.7 on 2025-12-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0005_alter_event_date_from_alter_event_date_till_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendar",
            name="key",
            field=models.CharField(
                help_text="Ключ необходимо указать с &tz_id=Europe/Moscow",
                max_length=255,
                verbose_name="Ключ от календаря",
            ),
        ),
    ]
