# Generated by Django 5.2.7 on 2026-01-19 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0006_alter_calendar_key"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="users",
            field=models.ManyToManyField(
                blank=True, related_name="events", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
