# Generated by Django 5.2.7 on 2026-01-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0007_alter_event_users"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="aiterus",
            field=models.BooleanField(default=False, verbose_name="Аитерус"),
        ),
    ]
