# Generated by Django 5.2.7 on 2026-02-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0008_event_aiterus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="calendar",
        ),
        migrations.AddField(
            model_name="event",
            name="calendar",
            field=models.ManyToManyField(related_name="events", to="event.calendar"),
        ),
    ]
