# Generated by Django 5.2.7 on 2026-02-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0009_remove_event_calendar_event_calendar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="calendar",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="event.calendar"
            ),
        ),
    ]
