# Generated by Django 5.2.7 on 2026-02-11 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0010_alter_event_calendar"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Наименование чата"
                    ),
                ),
                (
                    "chat_id",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Id группового чата"
                    ),
                ),
                (
                    "calendar",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="groups",
                        to="event.calendar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Групповой чат",
                "verbose_name_plural": "Групповые чаты",
            },
        ),
    ]
