# Generated by Django 5.2.7 on 2026-02-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0011_groupchat"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="events", to="event.groupchat"
            ),
        ),
    ]
