# Generated by Django 5.2.7 on 2026-02-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0012_event_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupchat",
            name="calendar_show_time",
            field=models.TimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Время отображения календаря",
            ),
        ),
    ]
