# Generated by Django 5.2.7 on 2026-02-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0013_groupchat_calendar_show_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="message",
            field=models.TextField(
                blank=True, null=True, verbose_name="Текст сообщения"
            ),
        ),
    ]
