# Generated by Django 5.2.7 on 2026-02-25 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0014_event_message"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SendedMessages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.event",
                        unique=True,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(blank=True, null=True, to="event.groupchat"),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True, null=True, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "Отправленное сообщение",
                "verbose_name_plural": "Отправленные сообщения",
                "default_related_name": "messages",
            },
        ),
    ]
