# Generated by Django 5.2.7 on 2026-02-26 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0015_sendedmessages"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="sendedmessages",
            name="event",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="event.event"
            ),
        ),
        migrations.AlterField(
            model_name="sendedmessages",
            name="groups",
            field=models.ManyToManyField(blank=True, to="event.groupchat"),
        ),
        migrations.AlterField(
            model_name="sendedmessages",
            name="users",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
