"""
Django settings for calendar_backend project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import logging.config
import os
from pathlib import Path
from dotenv import load_dotenv
from celery.schedules import crontab

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG")

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

CORS_ALLOWED_ORIGINS = os.getenv(
    "DJANGO_ALLOWED_ORIGINS",
    "http://localhost,http://127.0.0.1",
).split(",")

CSRF_TRUSTED_ORIGINS = os.getenv(
    "DJANGO_ALLOWED_ORIGINS",
    "http://localhost,http://127.0.0.1",
).split(",")

# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "silk",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_celery_beat",
    "rest_framework",
    "core.apps.CoreConfig",
    "event.apps.EventConfig",
    "users.apps.UsersConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.middleware.telegram_middleware.TelegramIDMiddleware",
    "silk.middleware.SilkyMiddleware",
]

ROOT_URLCONF = "calendar_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.request",
            ],
        },
    },
]

WSGI_APPLICATION = "calendar_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "calendar"),
        "USER": os.getenv("POSTGRES_USER", "calendar"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", ""),
        "HOST": os.getenv("POSTGRES_HOST", "localhost"),
        "PORT": os.getenv("POSTGRES_PORT", 5432),
    },
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "ru-ru"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = BASE_DIR / "static"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "users.User"

# Тестовые настройки SMTP
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = os.getenv("EMAIL_PORT")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() == "true"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False").lower() == "true"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

# CELERY
CALENDAR_UPDATE_PERIOD = 10
REDIS_HOST = os.getenv("REDIS_HOST")
CELERY_BROKER_URL = f"redis://{REDIS_HOST}:6379"
CELERY_RESULT_BACKEND = f"redis://{REDIS_HOST}:6379"
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_TIMEZONE = "Europe/Moscow"
CELERY_RESULT_SERIALIZER = "json"
CELERY_WORKER_REVOKES_MAXCELERY_WORKER_REVOKE_EXPIRES = 0
CELERY_BEAT_SCHEDULE = {
    "update_calendar": {
        "task": "event.tasks.start_update_calendar",
        "schedule": crontab(minute=f"*/{CALENDAR_UPDATE_PERIOD}"),
    },
    "delete_old_events_every_day": {
        "task": "event.tasks.clear_old_events",
        "schedule": crontab(hour=0, minute=0),
    },
    "clear_empty_crontab_every_day": {
        "task": "users.tasks.clear_crontab",
        "schedule": crontab(hour=0, minute=0),
    },
}

# BOT
BOT_TOKEN = os.getenv("BOT_TOKEN")


# LOGGING
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "app": {
            "format": "[%(asctime)s] [%(levelname)s] [%(method)s-%(status)s] > %(message)s",
            "datefmt": "%d-%m-%y %H:%M:%S",
        },
        "calendar": {
            "format": "[%(asctime)s] [%(levelname)s] [%(module)s] > %(message)s",
            "datefmt": "%d-%m-%y %H:%M:%S",
        },
        "bot": {
            "format": "[[%(asctime)s] [%(levelname)s] > %(message)s",
        },
        "email": {
            "format": "[%(asctime)s] [%(levelname)s] [%(module)s] > %(message)s",
            "datefmt": "%d-%m-%y %H:%M:%S",
        },
    },
    "handlers": {
        "app": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": os.path.join("..", BASE_DIR, "django.log"),
            "formatter": "app",
        },
        "calendar": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": os.path.join("..", BASE_DIR, "django.log"),
            "formatter": "calendar",
        },
        "bot": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": os.path.join("..", BASE_DIR, "bot.log"),
            "formatter": "bot",
        },
        "email_handler": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": os.path.join("..", BASE_DIR, "django.log"),
            "formatter": "email",
        },
    },
    "loggers": {
        "app": {
            "handlers": ["app"],
            "level": "DEBUG",
            "propagate": True,
        },
        "calendar": {
            "handlers": ["calendar"],
            "level": "DEBUG",
            "propagate": True,
        },
        "bot": {
            "handlers": ["bot"],
            "level": "INFO",
            "propagate": True,
        },
        "email": {
            "handlers": ["email_handler"],
            "level": "INFO",
            "propagate": True,
        },
    },
}

logging.config.dictConfig(LOGGING)

# Jazzmin
JAZZMIN_SETTINGS = {
    "site_title": "Call-calendar Панель управления",
    "site_header": "Call-calendar",
    "site_brand": "Call-calendar",
    "welcome_sign": "Добро пожаловать в панель администратора Call-calendar",
    "show_sidebar": True,
    "navigation_expanded": True,
    # Hide these apps when generating side menu e.g (auth)
    "hide_apps": [],
    # Hide these models when generating side menu (e.g auth.user)
    "hide_models": [
        "auth.group",
        "django_celery_beat.solarschedule",
        "django_celery_beat.intervalschedule",
    ],
    # List of apps (and/or models) to base side menu ordering off of (does not need to contain all apps/models)
    "order_with_respect_to": [
        "users",
        "users.User",
        "event",
        "event.GroupChat",
        "event.Event",
        "event.Calendar" "django_celery_beat",
        "django_celery_beat.crontabschedule",
        "django_celery_beat.clockedschedule",
        "django_celery_beat.periodictask",
    ],
    # Custom icons for side menu apps/models See https://fontawesome.com/icons?d=gallery&m=free&v=5.0.0,5.0.1,5.0.10,5.0.11,5.0.12,5.0.13,5.0.2,5.0.3,5.0.4,5.0.5,5.0.6,5.0.7,5.0.8,5.0.9,5.1.0,5.1.1,5.2.0,5.3.0,5.3.1,5.4.0,5.4.1,5.4.2,5.13.0,5.12.0,5.11.2,5.11.1,5.10.0,5.9.0,5.8.2,5.8.1,5.7.2,5.7.1,5.7.0,5.6.3,5.5.0,5.4.2
    # for the full list of 5.13.0 free icon classes
    "icons": {
        "users.User": "fa-solid fa-person",
        "event.GroupChat": "fa-solid fa-people-group",
        "event.Event": "fa-solid fa-calendar-plus",
        "event.Calendar": "fa-regular fa-calendar",
        "django_celery_beat.crontabschedule": "fa-solid fa-clock",
        "django_celery_beat.clockedschedule": "fa-solid fa-thumbtack",
        "django_celery_beat.periodictask": "fa-solid fa-list",
    },
    # Icons that are used when one is not manually specified
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
}

JAZZMIN_UI_TWEAKS = {
    "theme": "sandstone",
}
