"""
Django settings for calendar_backend project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import logging.config
import os
from pathlib import Path
from dotenv import load_dotenv
from celery.schedules import crontab

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.

BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG")

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_celery_beat",
    "rest_framework",
    "core.apps.CoreConfig",
    "event.apps.EventConfig",
    "users.apps.UsersConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.middleware.telegram_middleware.TelegramIDMiddleware",
]

ROOT_URLCONF = "calendar_backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "calendar_backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "calendar"),
        "USER": os.getenv("POSTGRES_USER", "calendar"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", ""),
        "HOST": os.getenv("POSTGRES_HOST", "localhost"),
        "PORT": os.getenv("POSTGRES_PORT", 5432),
    },
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "ru-ru"

TIME_ZONE = "Europe/Moscow"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

STATIC_ROOT = BASE_DIR / "static"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "users.User"

# Тестовые настройки SMTP
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = os.getenv("EMAIL_PORT")
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True").lower() == "true"
EMAIL_USE_SSL = os.getenv("EMAIL_USE_SSL", "False").lower() == "true"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL")

# CELERY
REDIS_HOST = os.getenv("REDIS_HOST")
CELERY_BROKER_URL = f"redis://{REDIS_HOST}:6379"
CELERY_RESULT_BACKEND = f"redis://{REDIS_HOST}:6379"
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_TIMEZONE = "Europe/Moscow"
CELERY_RESULT_SERIALIZER = "json"
CELERY_WORKER_REVOKES_MAXCELERY_WORKER_REVOKE_EXPIRES = 0
CELERY_BEAT_SCHEDULE = {
    "update_calendar_every_15_minutes": {
        "task": "event.tasks.start_update_calendar",
        "schedule": crontab(minute="*/15"),
    },
    "delete_old_events_every_day": {
        "task": "event.tasks.clear_old_events",
        "schedule": crontab(hour=0, minute=0),
    },
}

# BOT
BOT_TOKEN = os.getenv("BOT_TOKEN")


# LOGGING
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "app": {
            "format": "[%(asctime)s] [%(levelname)s] [%(method)s-%(status)s] > %(message)s",
            "datefmt": "%d-%m-%y %H:%M:%S",
        },
        "calendar": {
            "format": "[%(asctime)s] [%(levelname)s] [%(module)s] > %(message)s",
            "datefmt": "%d-%m-%y %H:%M:%S",
        },
        "bot": {
            "format": "[[%(asctime)s] [%(levelname)s] > %(message)s",
        },
        "email": {
            "format": "[%(asctime)s] [%(levelname)s] [%(module)s] > %(message)s",
            "datefmt": "%d-%m-%y %H:%M:%S",
        },
    },
    "handlers": {
        "app": {
            "level": "DEBUG",
            "class": "logging.FileHandler",
            "filename": os.path.join("..", BASE_DIR, "django.log"),
            "formatter": "app",
        },
        "calendar": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": os.path.join("..", BASE_DIR, "django.log"),
            "formatter": "calendar",
        },
        "bot": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": os.path.join("..", BASE_DIR, "bot.log"),
            "formatter": "bot",
        },
        "email_handler": {
            "level": "INFO",
            "class": "logging.FileHandler",
            "filename": os.path.join("..", BASE_DIR, "django.log"),
            "formatter": "email",
        },
    },
    "loggers": {
        "app": {
            "handlers": ["app"],
            "level": "DEBUG",
            "propagate": True,
        },
        "calendar": {
            "handlers": ["calendar"],
            "level": "DEBUG",
            "propagate": True,
        },
        "bot": {
            "handlers": ["bot"],
            "level": "INFO",
            "propagate": True,
        },
        "email": {
            "handlers": ["email_handler"],
            "level": "INFO",
            "propagate": True,
        },
    },
}

logging.config.dictConfig(LOGGING)
