# Generated by Django 5.2.7 on 2025-11-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="show_slash_events",
            field=models.BooleanField(
                default=False, verbose_name="Показывать мероприятия со слэшем"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="show_star_events",
            field=models.BooleanField(
                default=False, verbose_name="Показывать мероприятия со звездочкой"
            ),
        ),
    ]
