# Generated by Django 5.2.7 on 2025-11-27 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0002_alter_event_calendar"),
        ("users", "0002_alter_user_calendar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="calendar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="event.calendar",
            ),
        ),
    ]
