# Generated by Django 5.2.7 on 2026-01-20 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_calendar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="calendar_show_time",
            field=models.TimeField(
                default=datetime.time(10, 0), verbose_name="Время отображения календаря"
            ),
        ),
    ]
