# Generated by Django 5.2.7 on 2026-01-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_calendar_show_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="calendar_show_time",
            field=models.TimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Время отображения календаря",
            ),
        ),
    ]
