# Generated by Django 5.2.7 on 2026-02-04 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0010_alter_event_calendar"),
        ("users", "0006_user_show_aiterus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="calendar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="event.calendar",
            ),
        ),
    ]
