# Generated by Django 5.2.7 on 2026-02-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_user_calendar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Электронная почта"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_id",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="ID телеграм"
            ),
        ),
    ]
