# Generated by Django 5.2.7 on 2026-02-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_user_email_alter_user_telegram_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="calendar_show_time",
            field=models.TimeField(
                blank=True,
                default="08:00",
                null=True,
                verbose_name="Время отображения календаря",
            ),
        ),
    ]
